### ISSUE TITLE
Python3 incompatibility: 'unicode' reference in response.py

### ISSUE THREAD

**Issue by reverie** [timotheus/ebaysdk-python#88]
response.py line 65 has "if i is None or isinstance(i, str) or isinstance(i, unicode):", resulting in "NameError: name 'unicode' is not defined" under python3

**Comment by jamesbeith** [comment]
I'm seeing this too when making a variety of API requests. @timotheus it would be great to get @reverie PR merged.

**Comment by LaundroMat** [comment]
+1 -- I'm having the same problem. I'm using Python 3.3.2 and the [current master version[(https://github.com/timotheus/ebaysdk-python/commit/0f2d65e1fbf18cdc68d172c110c345a6eb485e04) of this SDK.

**Comment by reverie** [comment]
FWIW I'm using git+git://github.com/reverie/ebaysdk-python.git in production and it seems fine

**Comment by timotheus** [comment]
I'll take a look and merge it.

**Comment by timotheus** [comment]
Can someone please clarify what is breaking on py3? The following works fine on py2. However, py3 throws this value error. Is this the issue? If not, can someone provide a test or some sample code?

ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

```python
# -*- coding: utf-8 -*-

import os
import sys

sys.path.insert(0, '%s/../' % os.path.dirname(__file__))

from ebaysdk.response import Response, ResponseDataObject

def main():
    xml = '''<?xml version='1.0' encoding='UTF-8'?>
        <findItemsByProductResponse xmlns="http://www.ebay.com/marketplace/search/v1/services">
            <ack>Success</ack>
            <version>1.12.0</version>
            <timestamp>2014-02-07T23:31:13.941Z</timestamp>
            <searchResult count="2">
                <item>
                </item>
            </searchResult>
            <paginationOutput>
                <pageNumber>1</pageNumber>
                <entriesPerPage>2</entriesPerPage>
                <totalPages>90</totalPages>
                <totalEntries>179</totalEntries>
            </paginationOutput>
            <itemSearchURL>Kościół http://www.ebay.com/ctg/53039031?_ddo=1&amp;_ipg=2&amp;_pgn=1</itemSearchURL>
        </findItemsByProductResponse>
    '''

    o = ResponseDataObject({'content': xml}, [])
    r = Response(o, verb='findItemsByProduct')

if __name__ == '__main__':
    main()
```

**Comment by timotheus** [comment]
Never mind, I found the error.

**Comment by esundward** [comment]
is it intended that the problemn is still present in the master branch?

**Comment by RobbieClarken** [comment]
This issue seems to be fixed in master (thanks!) - it would be great if a new release could be uploaded to PyPI so the fix is available for users who `pip install ebaysdk`.

**Comment by timotheus** [comment]
I'll upload a new version to pypi this week.

**Comment by rsmulktis** [comment]
Any idea when you'll get to this? I installed via pip and couldn't make requests then found this issue. Would prefer to just update from pip if its going to be soon. Thanks!

**Comment by timotheus** [comment]
Hi - I just pushed a new version (2.1.3) to pypi. Sorry for the delay.

**Comment by listingmirror** [comment]
@timotheus I am still seeing this error, perhaps a different flavor of it?


`
  File "/webapps/app/lib/python3.5/site-packages/ebaysdk/trading/__init__.py", line 704, in build_request_data
    xml += dict2xml(data, self.escape_xml)
  File "/webapps/app/lib/python3.5/site-packages/ebaysdk/utils.py", line 228, in dict2xml
    value = dict2xml(root[key], escape_xml)
  File "/webapps/app/lib/python3.5/site-packages/ebaysdk/utils.py", line 228, in dict2xml
    value = dict2xml(root[key], escape_xml)
  File "/webapps/app/lib/python3.5/site-packages/ebaysdk/utils.py", line 228, in dict2xml
    value = dict2xml(root[key], escape_xml)
  File "/webapps/app/lib/python3.5/site-packages/ebaysdk/utils.py", line 246, in dict2xml
    value = dict2xml(item, escape_xml)
  File "/webapps/app/lib/python3.5/site-packages/ebaysdk/utils.py", line 266, in dict2xml
    or isinstance(root, unicode) or isinstance(root, long) \
NameError: name 'unicode' is not defined
`
